### ISSUE TITLE
Renovate won't work on any YAML files with embedded Jinja2 logic

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/flux-cluster-template#959]
Example errors from the renovate logs:

```
Failed to parse helm-values YAML
{
  "err": {
    "name": "YAMLException",
    "reason": "missed comma between flow collection entries",
    "mark": {
      "name": null,
      "buffer": "#jinja2: trim_blocks: True, lstrip_blocks: True\n---\napiVersion: helm.toolkit.fluxcd.io/v2beta1\nkind: HelmRelease\nmetadata:\n  name: kube-prometheus-stack\n  namespace: monitoring\nspec:\n  interval: 30m\n  timeout: 15m\n  chart:\n    spec:\n      chart: kube-prometheus-stack\n      version: 48.1.2\n      sourceRef:\n        kind: HelmRepository\n        name: prometheus-community\n        namespace: flux-system\n  maxHistory: 2\n  install:\n    crds: CreateReplace\n    remediation:\n      retries: 3\n  upgrade:\n    cleanupOnFail: true\n    crds: CreateReplace\n    remediation:\n      retries: 3\n  uninstall:\n    keepHistory: false\n  dependsOn:\n    - name: local-path-provisioner\n      namespace: kube-system\n  values:\n    crds:\n      enabled: true\n    cleanPrometheusOperatorObjectNames: true\n    alertmanager:\n      enabled: false\n    kube-state-metrics:\n      metricLabelsAllowlist:\n        - \"deployments=[*]\"\n        - \"persistentvolumeclaims=[*]\"\n        - \"pods=[*]\"\n      prometheus:\n        monitor:\n          enabled: true\n          relabelings:\n            - action: replace\n              sourceLabels: [\"__meta_kubernetes_pod_node_name\"]\n              regex: ^(.*)$\n              replacement: $1\n              targetLabel: kubernetes_node\n    kubelet:\n      enabled: true\n      serviceMonitor:\n        metricRelabelings:\n          # Remove duplicate labels provided by k3s\n          - action: keep\n            sourceLabels: [\"__name__\"]\n            regex: (apiserver_audit|apiserver_client|apiserver_delegated|apiserver_envelope|apiserver_storage|apiserver_webhooks|authentication_token|cadvisor_version|container_blkio|container_cpu|container_fs|container_last|container_memory|container_network|container_oom|container_processes|container|csi_operations|disabled_metric|get_token|go|hidden_metric|kubelet_certificate|kubelet_cgroup|kubelet_container|kubelet_containers|kubelet_cpu|kubelet_device|kubelet_graceful|kubelet_http|kubelet_lifecycle|kubelet_managed|kubelet_node|kubelet_pleg|kubelet_pod|kubelet_run|kubelet_running|kubelet_runtime|kubelet_server|kubelet_started|kubelet_volume|kubernetes_build|kubernetes_feature|machine_cpu|machine_memory|machine_nvm|machine_scrape|node_namespace|plugin_manager|prober_probe|process_cpu|process_max|process_open|process_resident|process_start|process_virtual|registered_metric|rest_client|scrape_duration|scrape_samples|scrape_series|storage_operation|volume_manager|volume_operation|workqueue)_(.+)\n          - action: replace\n            sourceLabels: [\"node\"]\n            targetLabel: instance\n          # Drop high cardinality labels\n          - action: labeldrop\n            regex: (uid)\n          - action: labeldrop\n            regex: (id|name)\n          - action: drop\n            sourceLabels: [\"__name__\"]\n            regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)\n    kubeApiServer:\n      enabled: true\n      serviceMonitor:\n        metricRelabelings:\n          # Remove duplicate labels provided by k3s\n          - action: keep\n            sourceLabels: [\"__name__\"]\n            regex: (aggregator_openapi|aggregator_unavailable|apiextensions_openapi|apiserver_admission|apiserver_audit|apiserver_cache|apiserver_cel|apiserver_client|apiserver_crd|apiserver_current|apiserver_envelope|apiserver_flowcontrol|apiserver_init|apiserver_kube|apiserver_longrunning|apiserver_request|apiserver_requested|apiserver_response|apiserver_selfrequest|apiserver_storage|apiserver_terminated|apiserver_tls|apiserver_watch|apiserver_webhooks|authenticated_user|authentication|disabled_metric|etcd_bookmark|etcd_lease|etcd_request|field_validation|get_token|go|grpc_client|hidden_metric|kube_apiserver|kubernetes_build|kubernetes_feature|node_authorizer|pod_security|process_cpu|process_max|process_open|process_resident|process_start|process_virtual|registered_metric|rest_client|scrape_duration|scrape_samples|scrape_series|serviceaccount_legacy|serviceaccount_stale|serviceaccount_valid|watch_cache|workqueue)_(.+)\n          # Drop high cardinality labels\n          - action: drop\n            sourceLabels: [\"__name__\"]\n            regex: (apiserver|etcd|rest_client)_request(|_sli|_slo)_duration_seconds_bucket\n          - action: drop\n            sourceLabels: [\"__name__\"]\n            regex: (apiserver_response_sizes_bucket|apiserver_watch_events_sizes_bucket)\n    kubeControllerManager:\n      enabled: true\n      endpoints: &cp\n      {% for item in bootstrap_nodes.master %}\n        - {{ item.address }}\n      {% endfor %}\n      serviceMonitor:\n        metricRelabelings:\n          # Remove duplicate labels provided by k3s\n          - action: keep\n            sourceLabels: [\"__name__\"]\n            regex: \"(apiserver_audit|apiserver_client|apiserver_delegated|apiserver_envelope|apiserver_storage|apiserver_webhooks|attachdetach_controller|authenticated_user|authentication|cronjob_controller|disabled_metric|endpoint_slice|ephemeral_volume|garbagecollector_controller|get_token|go|hidden_metric|job_controller|kubernetes_build|kubernetes_feature|leader_election|node_collector|node_ipam|process_cpu|process_max|process_open|process_resident|process_start|process_virtual|pv_collector|registered_metric|replicaset_controller|rest_client|retroactive_storageclass|root_ca|running_managed|scrape_duration|scrape_samples|scrape_series|service_controller|storage_count|storage_operation|ttl_after|volume_operation|workqueue)_(.+)\"\n    kubeEtcd:\n      enabled: true\n      endpoints: *cp\n    kubeScheduler:\n      enabled: true\n      endpoints: *cp\n      serviceMonitor:\n        metricRelabelings:\n          # Remove duplicate labels provided by k3s\n          - action: keep\n            sourceLabels: [\"__name__\"]\n            regex: \"(apiserver_audit|apiserver_client|apiserver_delegated|apiserver_envelope|apiserver_storage|apiserver_webhooks|authenticated_user|authentication|disabled_metric|go|hidden_metric|kubernetes_build|kubernetes_feature|leader_election|process_cpu|process_max|process_open|process_resident|process_start|process_virtual|registered_metric|rest_client|scheduler|scrape_duration|scrape_samples|scrape_series|workqueue)_(.+)\"\n    kubeProxy:\n      enabled: false # Disabled due to eBPF\n    prometheus:\n      ingress:\n        enabled: true\n        ingressClassName: internal\n        annotations:\n          hajimari.io/appName: Prometheus\n          hajimari.io/icon: simple-icons:prometheus\n        pathType: Prefix\n        hosts:\n          - &host \"prometheus.${SECRET_DOMAIN}\"\n        tls:\n          - hosts:\n              - *host\n      prometheusSpec:\n        ruleSelectorNilUsesHelmValues: false\n        serviceMonitorSelectorNilUsesHelmValues: false\n        podMonitorSelectorNilUsesHelmValues: false\n        probeSelectorNilUsesHelmValues: false\n        scrapeConfigSelectorNilUsesHelmValues: false\n        enableAdminAPI: true\n        walCompression: true\n        retentionSize: 8GB\n        storageSpec:\n          volumeClaimTemplate:\n            spec:\n              storageClassName: local-path\n              resources:\n                requests:\n                  storage: 10Gi\n    grafana:\n      enabled: false\n      forceDeployDashboards: true\n      sidecar:\n        dashboards:\n          multicluster:\n            etcd:\n              enabled: true\n",
      "position": 4472,
      "line": 90,
      "column": 7,
      "snippet": " 88 |     kubeControllerManager:\n 89 |       enabled: true\n 90 |       endpoints: &cp\n 91 |       {% for item in bootstrap_nodes.m ...\n-------------^\n 92 |         - {{ item.address }}\n 93 |       {% endfor %}"
    },
    "message": "missed comma between flow collection entries (91:8)\n\n 88 |     kubeControllerManager:\n 89 |       enabled: true\n 90 |       endpoints: &cp\n 91 |       {% for item in bootstrap_nodes.m ...\n-------------^\n 92 |         - {{ item.address }}\n 93 |       {% endfor %}",
    "stack": "YAMLException: missed comma between flow collection entries (91:8)\n\n 88 |     kubeControllerManager:\n 89 |       enabled: true\n 90 |       endpoints: &cp\n 91 |       {% for item in bootstrap_nodes.m ...\n-------------^\n 92 |         - {{ item.address }}\n 93 |       {% endfor %}\n    at generateError (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:183:10)\n    at throwError (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:187:9)\n    at readFlowCollection (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:758:7)\n    at composeNode (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1442:11)\n    at readBlockMapping (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1104:12)\n    at composeNode (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1441:12)\n    at readBlockMapping (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1164:11)\n    at composeNode (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1441:12)\n    at readBlockMapping (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1164:11)\n    at composeNode (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1441:12)\n    at readBlockMapping (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1164:11)\n    at composeNode (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1441:12)\n    at readDocument (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1625:3)\n    at loadDocuments (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1688:5)\n    at loadAll (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1701:19)\n    at Object.extractPackageFile (/opt/containerbase/tools/renovate/37.0.3/node_modules/renovate/lib/modules/manager/helm-values/extract.ts:69:28)\n    at extractPackageFile (/opt/containerbase/tools/renovate/37.0.3/node_modules/renovate/lib/modules/manager/index.ts:75:9)\n    at getManagerPackageFiles (/opt/containerbase/tools/renovate/37.0.3/node_modules/renovate/lib/workers/repository/extract/manager-files.ts:45:43)\n    at /opt/containerbase/tools/renovate/37.0.3/node_modules/renovate/lib/workers/repository/extract/index.ts:64:28\n    at async Promise.all (index 4)"
  }
  "packageFile": "bootstrap/templates/addons/kube-prometheus-stack/app/helmrelease.yaml.j2"
}
```

```
Failed to parse Flux manifest
{
  "err": {
    "name": "YAMLException",
    "reason": "missed comma between flow collection entries",
    "mark": {
      "name": null,
      "buffer": "#jinja2: trim_blocks: True, lstrip_blocks: True\n---\napiVersion: helm.toolkit.fluxcd.io/v2beta1\nkind: HelmRelease\nmetadata:\n  name: kube-prometheus-stack\n  namespace: monitoring\nspec:\n  interval: 30m\n  timeout: 15m\n  chart:\n    spec:\n      chart: kube-prometheus-stack\n      version: 48.1.2\n      sourceRef:\n        kind: HelmRepository\n        name: prometheus-community\n        namespace: flux-system\n  maxHistory: 2\n  install:\n    crds: CreateReplace\n    remediation:\n      retries: 3\n  upgrade:\n    cleanupOnFail: true\n    crds: CreateReplace\n    remediation:\n      retries: 3\n  uninstall:\n    keepHistory: false\n  dependsOn:\n    - name: local-path-provisioner\n      namespace: kube-system\n  values:\n    crds:\n      enabled: true\n    cleanPrometheusOperatorObjectNames: true\n    alertmanager:\n      enabled: false\n    kube-state-metrics:\n      metricLabelsAllowlist:\n        - \"deployments=[*]\"\n        - \"persistentvolumeclaims=[*]\"\n        - \"pods=[*]\"\n      prometheus:\n        monitor:\n          enabled: true\n          relabelings:\n            - action: replace\n              sourceLabels: [\"__meta_kubernetes_pod_node_name\"]\n              regex: ^(.*)$\n              replacement: $1\n              targetLabel: kubernetes_node\n    kubelet:\n      enabled: true\n      serviceMonitor:\n        metricRelabelings:\n          # Remove duplicate labels provided by k3s\n          - action: keep\n            sourceLabels: [\"__name__\"]\n            regex: (apiserver_audit|apiserver_client|apiserver_delegated|apiserver_envelope|apiserver_storage|apiserver_webhooks|authentication_token|cadvisor_version|container_blkio|container_cpu|container_fs|container_last|container_memory|container_network|container_oom|container_processes|container|csi_operations|disabled_metric|get_token|go|hidden_metric|kubelet_certificate|kubelet_cgroup|kubelet_container|kubelet_containers|kubelet_cpu|kubelet_device|kubelet_graceful|kubelet_http|kubelet_lifecycle|kubelet_managed|kubelet_node|kubelet_pleg|kubelet_pod|kubelet_run|kubelet_running|kubelet_runtime|kubelet_server|kubelet_started|kubelet_volume|kubernetes_build|kubernetes_feature|machine_cpu|machine_memory|machine_nvm|machine_scrape|node_namespace|plugin_manager|prober_probe|process_cpu|process_max|process_open|process_resident|process_start|process_virtual|registered_metric|rest_client|scrape_duration|scrape_samples|scrape_series|storage_operation|volume_manager|volume_operation|workqueue)_(.+)\n          - action: replace\n            sourceLabels: [\"node\"]\n            targetLabel: instance\n          # Drop high cardinality labels\n          - action: labeldrop\n            regex: (uid)\n          - action: labeldrop\n            regex: (id|name)\n          - action: drop\n            sourceLabels: [\"__name__\"]\n            regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)\n    kubeApiServer:\n      enabled: true\n      serviceMonitor:\n        metricRelabelings:\n          # Remove duplicate labels provided by k3s\n          - action: keep\n            sourceLabels: [\"__name__\"]\n            regex: (aggregator_openapi|aggregator_unavailable|apiextensions_openapi|apiserver_admission|apiserver_audit|apiserver_cache|apiserver_cel|apiserver_client|apiserver_crd|apiserver_current|apiserver_envelope|apiserver_flowcontrol|apiserver_init|apiserver_kube|apiserver_longrunning|apiserver_request|apiserver_requested|apiserver_response|apiserver_selfrequest|apiserver_storage|apiserver_terminated|apiserver_tls|apiserver_watch|apiserver_webhooks|authenticated_user|authentication|disabled_metric|etcd_bookmark|etcd_lease|etcd_request|field_validation|get_token|go|grpc_client|hidden_metric|kube_apiserver|kubernetes_build|kubernetes_feature|node_authorizer|pod_security|process_cpu|process_max|process_open|process_resident|process_start|process_virtual|registered_metric|rest_client|scrape_duration|scrape_samples|scrape_series|serviceaccount_legacy|serviceaccount_stale|serviceaccount_valid|watch_cache|workqueue)_(.+)\n          # Drop high cardinality labels\n          - action: drop\n            sourceLabels: [\"__name__\"]\n            regex: (apiserver|etcd|rest_client)_request(|_sli|_slo)_duration_seconds_bucket\n          - action: drop\n            sourceLabels: [\"__name__\"]\n            regex: (apiserver_response_sizes_bucket|apiserver_watch_events_sizes_bucket)\n    kubeControllerManager:\n      enabled: true\n      endpoints: &cp\n      {% for item in bootstrap_nodes.master %}\n        - {{ item.address }}\n      {% endfor %}\n      serviceMonitor:\n        metricRelabelings:\n          # Remove duplicate labels provided by k3s\n          - action: keep\n            sourceLabels: [\"__name__\"]\n            regex: \"(apiserver_audit|apiserver_client|apiserver_delegated|apiserver_envelope|apiserver_storage|apiserver_webhooks|attachdetach_controller|authenticated_user|authentication|cronjob_controller|disabled_metric|endpoint_slice|ephemeral_volume|garbagecollector_controller|get_token|go|hidden_metric|job_controller|kubernetes_build|kubernetes_feature|leader_election|node_collector|node_ipam|process_cpu|process_max|process_open|process_resident|process_start|process_virtual|pv_collector|registered_metric|replicaset_controller|rest_client|retroactive_storageclass|root_ca|running_managed|scrape_duration|scrape_samples|scrape_series|service_controller|storage_count|storage_operation|ttl_after|volume_operation|workqueue)_(.+)\"\n    kubeEtcd:\n      enabled: true\n      endpoints: *cp\n    kubeScheduler:\n      enabled: true\n      endpoints: *cp\n      serviceMonitor:\n        metricRelabelings:\n          # Remove duplicate labels provided by k3s\n          - action: keep\n            sourceLabels: [\"__name__\"]\n            regex: \"(apiserver_audit|apiserver_client|apiserver_delegated|apiserver_envelope|apiserver_storage|apiserver_webhooks|authenticated_user|authentication|disabled_metric|go|hidden_metric|kubernetes_build|kubernetes_feature|leader_election|process_cpu|process_max|process_open|process_resident|process_start|process_virtual|registered_metric|rest_client|scheduler|scrape_duration|scrape_samples|scrape_series|workqueue)_(.+)\"\n    kubeProxy:\n      enabled: false # Disabled due to eBPF\n    prometheus:\n      ingress:\n        enabled: true\n        ingressClassName: internal\n        annotations:\n          hajimari.io/appName: Prometheus\n          hajimari.io/icon: simple-icons:prometheus\n        pathType: Prefix\n        hosts:\n          - &host \"prometheus.${SECRET_DOMAIN}\"\n        tls:\n          - hosts:\n              - *host\n      prometheusSpec:\n        ruleSelectorNilUsesHelmValues: false\n        serviceMonitorSelectorNilUsesHelmValues: false\n        podMonitorSelectorNilUsesHelmValues: false\n        probeSelectorNilUsesHelmValues: false\n        scrapeConfigSelectorNilUsesHelmValues: false\n        enableAdminAPI: true\n        walCompression: true\n        retentionSize: 8GB\n        storageSpec:\n          volumeClaimTemplate:\n            spec:\n              storageClassName: local-path\n              resources:\n                requests:\n                  storage: 10Gi\n    grafana:\n      enabled: false\n      forceDeployDashboards: true\n      sidecar:\n        dashboards:\n          multicluster:\n            etcd:\n              enabled: true\n",
      "position": 4472,
      "line": 90,
      "column": 7,
      "snippet": " 88 |     kubeControllerManager:\n 89 |       enabled: true\n 90 |       endpoints: &cp\n 91 |       {% for item in bootstrap_nodes.m ...\n-------------^\n 92 |         - {{ item.address }}\n 93 |       {% endfor %}"
    },
    "message": "missed comma between flow collection entries (91:8)\n\n 88 |     kubeControllerManager:\n 89 |       enabled: true\n 90 |       endpoints: &cp\n 91 |       {% for item in bootstrap_nodes.m ...\n-------------^\n 92 |         - {{ item.address }}\n 93 |       {% endfor %}",
    "stack": "YAMLException: missed comma between flow collection entries (91:8)\n\n 88 |     kubeControllerManager:\n 89 |       enabled: true\n 90 |       endpoints: &cp\n 91 |       {% for item in bootstrap_nodes.m ...\n-------------^\n 92 |         - {{ item.address }}\n 93 |       {% endfor %}\n    at generateError (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:183:10)\n    at throwError (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:187:9)\n    at readFlowCollection (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:758:7)\n    at composeNode (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1442:11)\n    at readBlockMapping (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1104:12)\n    at composeNode (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1441:12)\n    at readBlockMapping (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1164:11)\n    at composeNode (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1441:12)\n    at readBlockMapping (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1164:11)\n    at composeNode (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1441:12)\n    at readBlockMapping (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1164:11)\n    at composeNode (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1441:12)\n    at readDocument (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1625:3)\n    at loadDocuments (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1688:5)\n    at loadAll (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1701:19)\n    at readManifest (/opt/containerbase/tools/renovate/37.0.3/node_modules/renovate/lib/modules/manager/flux/extract.ts:55:24)\n    at Object.extractAllPackageFiles (/opt/containerbase/tools/renovate/37.0.3/node_modules/renovate/lib/modules/manager/flux/extract.ts:304:22)\n    at extractAllPackageFiles (/opt/containerbase/tools/renovate/37.0.3/node_modules/renovate/lib/modules/manager/index.ts:53:17)\n    at getManagerPackageFiles (/opt/containerbase/tools/renovate/37.0.3/node_modules/renovate/lib/workers/repository/extract/manager-files.ts:33:29)\n    at /opt/containerbase/tools/renovate/37.0.3/node_modules/renovate/lib/workers/repository/extract/index.ts:64:28"
  }
  "packageFile": "bootstrap/templates/addons/kube-prometheus-stack/app/helmrelease.yaml.j2"
}
```

```
DEBUG: Failed to parse Kubernetes manifest.
{
  "err": {
    "name": "YAMLException",
    "reason": "missed comma between flow collection entries",
    "mark": {
      "name": null,
      "buffer": "#jinja2: trim_blocks: True, lstrip_blocks: True\n---\napiVersion: helm.toolkit.fluxcd.io/v2beta1\nkind: HelmRelease\nmetadata:\n  name: kube-prometheus-stack\n  namespace: monitoring\nspec:\n  interval: 30m\n  timeout: 15m\n  chart:\n    spec:\n      chart: kube-prometheus-stack\n      version: 48.1.2\n      sourceRef:\n        kind: HelmRepository\n        name: prometheus-community\n        namespace: flux-system\n  maxHistory: 2\n  install:\n    crds: CreateReplace\n    remediation:\n      retries: 3\n  upgrade:\n    cleanupOnFail: true\n    crds: CreateReplace\n    remediation:\n      retries: 3\n  uninstall:\n    keepHistory: false\n  dependsOn:\n    - name: local-path-provisioner\n      namespace: kube-system\n  values:\n    crds:\n      enabled: true\n    cleanPrometheusOperatorObjectNames: true\n    alertmanager:\n      enabled: false\n    kube-state-metrics:\n      metricLabelsAllowlist:\n        - \"deployments=[*]\"\n        - \"persistentvolumeclaims=[*]\"\n        - \"pods=[*]\"\n      prometheus:\n        monitor:\n          enabled: true\n          relabelings:\n            - action: replace\n              sourceLabels: [\"__meta_kubernetes_pod_node_name\"]\n              regex: ^(.*)$\n              replacement: $1\n              targetLabel: kubernetes_node\n    kubelet:\n      enabled: true\n      serviceMonitor:\n        metricRelabelings:\n          # Remove duplicate labels provided by k3s\n          - action: keep\n            sourceLabels: [\"__name__\"]\n            regex: (apiserver_audit|apiserver_client|apiserver_delegated|apiserver_envelope|apiserver_storage|apiserver_webhooks|authentication_token|cadvisor_version|container_blkio|container_cpu|container_fs|container_last|container_memory|container_network|container_oom|container_processes|container|csi_operations|disabled_metric|get_token|go|hidden_metric|kubelet_certificate|kubelet_cgroup|kubelet_container|kubelet_containers|kubelet_cpu|kubelet_device|kubelet_graceful|kubelet_http|kubelet_lifecycle|kubelet_managed|kubelet_node|kubelet_pleg|kubelet_pod|kubelet_run|kubelet_running|kubelet_runtime|kubelet_server|kubelet_started|kubelet_volume|kubernetes_build|kubernetes_feature|machine_cpu|machine_memory|machine_nvm|machine_scrape|node_namespace|plugin_manager|prober_probe|process_cpu|process_max|process_open|process_resident|process_start|process_virtual|registered_metric|rest_client|scrape_duration|scrape_samples|scrape_series|storage_operation|volume_manager|volume_operation|workqueue)_(.+)\n          - action: replace\n            sourceLabels: [\"node\"]\n            targetLabel: instance\n          # Drop high cardinality labels\n          - action: labeldrop\n            regex: (uid)\n          - action: labeldrop\n            regex: (id|name)\n          - action: drop\n            sourceLabels: [\"__name__\"]\n            regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)\n    kubeApiServer:\n      enabled: true\n      serviceMonitor:\n        metricRelabelings:\n          # Remove duplicate labels provided by k3s\n          - action: keep\n            sourceLabels: [\"__name__\"]\n            regex: (aggregator_openapi|aggregator_unavailable|apiextensions_openapi|apiserver_admission|apiserver_audit|apiserver_cache|apiserver_cel|apiserver_client|apiserver_crd|apiserver_current|apiserver_envelope|apiserver_flowcontrol|apiserver_init|apiserver_kube|apiserver_longrunning|apiserver_request|apiserver_requested|apiserver_response|apiserver_selfrequest|apiserver_storage|apiserver_terminated|apiserver_tls|apiserver_watch|apiserver_webhooks|authenticated_user|authentication|disabled_metric|etcd_bookmark|etcd_lease|etcd_request|field_validation|get_token|go|grpc_client|hidden_metric|kube_apiserver|kubernetes_build|kubernetes_feature|node_authorizer|pod_security|process_cpu|process_max|process_open|process_resident|process_start|process_virtual|registered_metric|rest_client|scrape_duration|scrape_samples|scrape_series|serviceaccount_legacy|serviceaccount_stale|serviceaccount_valid|watch_cache|workqueue)_(.+)\n          # Drop high cardinality labels\n          - action: drop\n            sourceLabels: [\"__name__\"]\n            regex: (apiserver|etcd|rest_client)_request(|_sli|_slo)_duration_seconds_bucket\n          - action: drop\n            sourceLabels: [\"__name__\"]\n            regex: (apiserver_response_sizes_bucket|apiserver_watch_events_sizes_bucket)\n    kubeControllerManager:\n      enabled: true\n      endpoints: &cp\n      {% for item in bootstrap_nodes.master %}\n        - {{ item.address }}\n      {% endfor %}\n      serviceMonitor:\n        metricRelabelings:\n          # Remove duplicate labels provided by k3s\n          - action: keep\n            sourceLabels: [\"__name__\"]\n            regex: \"(apiserver_audit|apiserver_client|apiserver_delegated|apiserver_envelope|apiserver_storage|apiserver_webhooks|attachdetach_controller|authenticated_user|authentication|cronjob_controller|disabled_metric|endpoint_slice|ephemeral_volume|garbagecollector_controller|get_token|go|hidden_metric|job_controller|kubernetes_build|kubernetes_feature|leader_election|node_collector|node_ipam|process_cpu|process_max|process_open|process_resident|process_start|process_virtual|pv_collector|registered_metric|replicaset_controller|rest_client|retroactive_storageclass|root_ca|running_managed|scrape_duration|scrape_samples|scrape_series|service_controller|storage_count|storage_operation|ttl_after|volume_operation|workqueue)_(.+)\"\n    kubeEtcd:\n      enabled: true\n      endpoints: *cp\n    kubeScheduler:\n      enabled: true\n      endpoints: *cp\n      serviceMonitor:\n        metricRelabelings:\n          # Remove duplicate labels provided by k3s\n          - action: keep\n            sourceLabels: [\"__name__\"]\n            regex: \"(apiserver_audit|apiserver_client|apiserver_delegated|apiserver_envelope|apiserver_storage|apiserver_webhooks|authenticated_user|authentication|disabled_metric|go|hidden_metric|kubernetes_build|kubernetes_feature|leader_election|process_cpu|process_max|process_open|process_resident|process_start|process_virtual|registered_metric|rest_client|scheduler|scrape_duration|scrape_samples|scrape_series|workqueue)_(.+)\"\n    kubeProxy:\n      enabled: false # Disabled due to eBPF\n    prometheus:\n      ingress:\n        enabled: true\n        ingressClassName: internal\n        annotations:\n          hajimari.io/appName: Prometheus\n          hajimari.io/icon: simple-icons:prometheus\n        pathType: Prefix\n        hosts:\n          - &host \"prometheus.${SECRET_DOMAIN}\"\n        tls:\n          - hosts:\n              - *host\n      prometheusSpec:\n        ruleSelectorNilUsesHelmValues: false\n        serviceMonitorSelectorNilUsesHelmValues: false\n        podMonitorSelectorNilUsesHelmValues: false\n        probeSelectorNilUsesHelmValues: false\n        scrapeConfigSelectorNilUsesHelmValues: false\n        enableAdminAPI: true\n        walCompression: true\n        retentionSize: 8GB\n        storageSpec:\n          volumeClaimTemplate:\n            spec:\n              storageClassName: local-path\n              resources:\n                requests:\n                  storage: 10Gi\n    grafana:\n      enabled: false\n      forceDeployDashboards: true\n      sidecar:\n        dashboards:\n          multicluster:\n            etcd:\n              enabled: true\n",
      "position": 4472,
      "line": 90,
      "column": 7,
      "snippet": " 88 |     kubeControllerManager:\n 89 |       enabled: true\n 90 |       endpoints: &cp\n 91 |       {% for item in bootstrap_nodes.m ...\n-------------^\n 92 |         - {{ item.address }}\n 93 |       {% endfor %}"
    },
    "message": "missed comma between flow collection entries (91:8)\n\n 88 |     kubeControllerManager:\n 89 |       enabled: true\n 90 |       endpoints: &cp\n 91 |       {% for item in bootstrap_nodes.m ...\n-------------^\n 92 |         - {{ item.address }}\n 93 |       {% endfor %}",
    "stack": "YAMLException: missed comma between flow collection entries (91:8)\n\n 88 |     kubeControllerManager:\n 89 |       enabled: true\n 90 |       endpoints: &cp\n 91 |       {% for item in bootstrap_nodes.m ...\n-------------^\n 92 |         - {{ item.address }}\n 93 |       {% endfor %}\n    at generateError (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:183:10)\n    at throwError (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:187:9)\n    at readFlowCollection (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:758:7)\n    at composeNode (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1442:11)\n    at readBlockMapping (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1104:12)\n    at composeNode (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1441:12)\n    at readBlockMapping (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1164:11)\n    at composeNode (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1441:12)\n    at readBlockMapping (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1164:11)\n    at composeNode (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1441:12)\n    at readBlockMapping (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1164:11)\n    at composeNode (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1441:12)\n    at readDocument (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1625:3)\n    at loadDocuments (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1688:5)\n    at loadAll (/opt/containerbase/tools/renovate/37.0.3/node_modules/js-yaml/lib/loader.js:1701:19)\n    at extractApis (/opt/containerbase/tools/renovate/37.0.3/node_modules/renovate/lib/modules/manager/kubernetes/extract.ts:73:18)\n    at Object.extractPackageFile (/opt/containerbase/tools/renovate/37.0.3/node_modules/renovate/lib/modules/manager/kubernetes/extract.ts:34:8)\n    at extractPackageFile (/opt/containerbase/tools/renovate/37.0.3/node_modules/renovate/lib/modules/manager/index.ts:75:9)\n    at getManagerPackageFiles (/opt/containerbase/tools/renovate/37.0.3/node_modules/renovate/lib/workers/repository/extract/manager-files.ts:45:43)\n    at /opt/containerbase/tools/renovate/37.0.3/node_modules/renovate/lib/workers/repository/extract/index.ts:64:28"
  }
  "packageFile": "bootstrap/templates/addons/kube-prometheus-stack/app/helmrelease.yaml.j2"
}
```

**Comment by onedr0p** [comment]
I think the way to solve this would be to have a values.yaml `configmap` and use `valuesFrom` in the `HelmRelease` but really haven't thought it thru too much.

**Comment by onedr0p** [comment]
Currently this affects kube-prometheus-stack and cilium helm releases.

**Comment by onedr0p** [comment]
Fixed in https://github.com/onedr0p/flux-cluster-template/commit/9abcf47a58b9f4bc979c0dccd16785d94d3587f7
